### ISSUE TITLE
ValueError: Invalid value for `memo`, must not be `None`

### ISSUE THREAD

**Issue by SnorreSelmer** [stenjo/SbankenToYNAB#19]
Prøvde å sync'e kontoene mine i dag, og fikk denne feilen spyttet ut...

```
snorre@frigg:~/SbankenToYNAB$ python3 sync_accounts.py
Traceback (most recent call last):
  File "sync_accounts.py", line 85, in <module>
    api_response = api_instance.get_transactions_by_account(api_settings.budget_id, account_map['account'], since_date=startDate)
  File "/home/snorre/SbankenToYNAB/ynab/ynab/transactions_api.py", line 366, in get_transactions_by_account
    (data) = self.get_transactions_by_account_with_http_info(budget_id, account_id, **kwargs)  # noqa: E501
  File "/home/snorre/SbankenToYNAB/ynab/ynab/transactions_api.py", line 436, in get_transactions_by_account_with_http_info
    return self.api_client.call_api(
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 317, in call_api
    return self.__call_api(resource_path, method,
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 233, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 249, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 249, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 613, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 249, in __deserialize
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 249, in <listcomp>
    return [self.__deserialize(sub_data, sub_kls)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 272, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/home/snorre/SbankenToYNAB/ynab/api_client.py", line 615, in __deserialize_model
    instance = klass(**kwargs)
  File "/home/snorre/SbankenToYNAB/ynab/models/sub_transaction.py", line 68, in __init__
    self.memo = memo
  File "/home/snorre/SbankenToYNAB/ynab/models/sub_transaction.py", line 163, in memo
    raise ValueError("Invalid value for `memo`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `memo`, must not be `None`
```
Kjørte en `GetStatementsAllAccounts.py` etterpå, det fungerte helt fint.

Igjen så avsluttes ikke scriptet `sync_accounts.py` så jeg får tilbake shell, men jeg må bruke Ctrl+C for å komme ut. (Ubuntu Server 20.04, Python 3.8.5)

**Comment by SnorreSelmer** [comment]
Her er `sync_accounts.log`:
```
INFO:root:Python version: 3.8.5, Linux-5.4.0-65-generic-x86_64-with-glibc2.29

INFO:root:Fetched 5 transactions from Lønn in SBanken
INFO:root: API response {'data': {'transactions': [2]}}
INFO:root:Got 2 existing YNAB transactions from Lønn
INFO:root:Transaction: 2021-02-09,  amount: -1500.0, typecode: 200, text: Overføring til annen egen konto
INFO:root:Found matching internal transaction id: 6a7ac013-fbb4-48b0-9b7d-1fbe410c4dd4, name: None
INFO:root:Transaction: 2021-02-08,  amount: 3156.0, typecode: 14, text: Fra nav
INFO:root:Transaction: 2021-02-06,  amount: -1000.0, typecode: 200, text: Overføring til annen egen konto
INFO:root:Found matching internal transaction id: 6a7ac013-fbb4-48b0-9b7d-1fbe410c4dd4, name: None
INFO:root:Transaction: 2021-02-01,  amount: -2000.0, typecode: 200, text: Overføring til annen egen konto
INFO:root:Found matching internal transaction id: 6a7ac013-fbb4-48b0-9b7d-1fbe410c4dd4, name: None
INFO:root:Transaction: 2021-02-01,  amount: -6.0, typecode: 54, text: Kostnader sms-varsling januar
INFO:root: 4 YNAB transactions to be added
INFO:root: API response {'data': {'transaction': None}}
INFO:root: 1 YNAB transactions to be updated
INFO:root: API response {'data': {'transaction': None}}
INFO:root:Sync done for Lønn

INFO:root:Fetched 25 transactions from Bruk in SBanken
```

**Comment by SnorreSelmer** [comment]
Duplicate of #17
