### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thorep** [stenjo/SbankenToYNAB#22]
Tips til hvordan jeg fikser denne? Brukt denne koden i evigheter..men stoppa nå. pass osv fra sbanken er i orden

"Traceback (most recent call last):
  File "C:\dev\SbankenToYNAB\GetStatementsAllAccounts.py", line 44, in <module>
    main()
  File "C:\dev\SbankenToYNAB\GetStatementsAllAccounts.py", line 10, in main
    http_session = create_authenticated_http_session(api_settings.CLIENTID, api_settings.SECRET)
  File "C:\dev\SbankenToYNAB\Helpers.py", line 26, in create_authenticated_http_session
    session.fetch_token(
  File "C:\Users\preth0506\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Users\preth0506\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Users\preth0506\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "C:\Users\preth0506\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Users\preth0506\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client)"

**Comment by stenjo** [comment]
Usikker der. Ser ikke ut til at du får opprettet en session i det hele tatt. Regner med du har tatt i bruk siste versjon av koden?

**Comment by stenjo** [comment]
Har du fremdeles problemer eller er det hele løst?

**Comment by thorep** [comment]
Det ble løst, men nå har jeg problemer igjen

**Comment by thorep** [comment]
`Traceback (most recent call last):
  File "C:\dev\SbankenToYNAB\GetStatementsAllAccounts.py", line 38, in <module>
    main()
  File "C:\dev\SbankenToYNAB\GetStatementsAllAccounts.py", line 11, in main
    sbanken = Sbanken(api_settings.CUSTOMERID, api_settings.CLIENTID, api_settings.SECRET)
  File "C:\dev\SbankenToYNAB\sbanken\Sbanken.py", line 24, in __init__
    self.session.fetch_token(
  File "C:\dev\python\lib\site-packages\requests_oauthlib\oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\dev\python\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 429, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\dev\python\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\dev\python\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\dev\python\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 402, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientError: (invalid_client)`

Har trippelsjekket api og secret til sbanken. Også bestilt ny secret uten hell

**Comment by steoj** [comment]
Har du sjekket at du har krysset av på alle rettigheter?
![image](https://user-images.githubusercontent.com/46670655/121904356-66623f00-cd29-11eb-8d48-5069af165484.png)

**Comment by thorep** [comment]
Jeg hadde ikke huket av der. Gjort det nå. Fungerer fortsatt ikke, men skal prøve igjen senere.

**Comment by stenjo** [comment]
Det kan se ut til at oauthlib ikke er klar for Python 3.9 enda: https://pyreadiness.org/3.9/

**Comment by alekslyse** [comment]
Enda et problem med samme feilmelding
