### ISSUE TITLE
oauthlib error (invalid_scope)

### ISSUE THREAD

**Issue by SnorreSelmer** [stenjo/SbankenToYNAB#27]
This script has stopped updating, and just throws the following error now:
```
Traceback (most recent call last):
  File "/home/snorre/SbankenToYNAB/sync_accounts.py", line 20, in <module>
    sbanken = Sbanken(api_settings.CUSTOMERID, api_settings.CLIENTID, api_settings.SECRET)
  File "/home/snorre/SbankenToYNAB/sbanken/Sbanken.py", line 24, in __init__
    self.session.fetch_token(
  File "/home/snorre/.local/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 360, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidScopeError: (invalid_scope)
```
System is Ubuntu 20.04 LTS with Python 3.9. To my knowledge, this was working fine until today.
I've verified that the API-keys for Sbanken and YNAB are valid.

**Comment by SnorreSelmer** [comment]
Ah, ser at dette han være relatert til #22 ...

**Comment by SnorreSelmer** [comment]
Prøvde å kjøre scriptet manuelt med Python 3.8 (som gjør at det aldri avslutter helt av seg selv), og det feilet også. Kan virke som om det er et problem med oauthlib som har blit sluppet til Ubuntu nylig.

**Comment by SnorreSelmer** [comment]
Ser ut til at dette også var relatert til "Grants access to perform operations on APIBeta APIs (aka. developer portal)". Fikk en ny feil etterpå, men Poster heller den som en egen issue.

Utrolig kjipt av Sbanken å gjøre en slik endring uten noe som helst varsel.
