### ISSUE TITLE
RuntimeError: Request to transactions API returned with HTTP status code 500 with reason Internal Server Error.

### ISSUE THREAD

**Issue by SnorreSelmer** [stenjo/SbankenToYNAB#28]
Vet ærlig talt ikke om dette er Sbanken som roter eller om det er noe med requestene...
```
Traceback (most recent call last):
  File "/home/snorre/SbankenToYNAB/sync_accounts.py", line 35, in <module>
    accounts.append(sbanken.GetTransactionsForPeriod(mapping['ID'],startDate,endDate))
  File "/home/snorre/SbankenToYNAB/sbanken/Sbanken.py", line 151, in GetTransactionsForPeriod
    raise RuntimeError("Request to transactions API returned with HTTP status code {} with reason {}. Request was {}".format(response.status_code, response.reason, queryString))
RuntimeError: Request to transactions API returned with HTTP status code 500 with reason Internal Server Error. Request was https://publicapi.sbanken.no/apibeta/api/v1/Transactions/***?startDate=2021-06-16&endDate=2021-06-18
```
Så langt jeg kan se i Sbankens egen dokumentasjon så ser dette ikke feil ut.
Jeg har byttet til den nye oAuth-domenet, og sjekket at konto-ID'en er korrekt.

Samtidig, API v2 er ute, og det ser stort sett ut som den er drop-in for kallene du bruker...

**Comment by steoj** [comment]
Dette kan skyldes at enddate er i dag. Dette er nok i tilfelle en liten feil i koden her - har en patch lokalt jeg jobber med som fikser det.

**Comment by SnorreSelmer** [comment]
Er det mulig å teste denne branch'en?

**Comment by SnorreSelmer** [comment]
Kikket litt på koden, fikset  så endDate starter "i dag - 1 dag", og fikset så startDate bruker endDate i stedet for today, og da fungerte det som forventet igjen. :) Ser frem til neste oppdatering.

**Comment by stenjo** [comment]
Flott. Du kan også sjekke ut feature/Major_updates branchen.
bruk:
git pull
git checkout feature/Major_updates
